services:
  - type: web
    name: autovidpro
    env: node
    buildCommand: npm install && npm install ffmpeg-static && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
